# Introduction to Quantel #

First import the library

In [1]:
import quantel

Libint2 initialized successfully


Now we create a molecule. For the time being, we have to add atoms one-by-one.

In [29]:
R = 2
mol = quantel.Molecule()
mol.add_atom("H",0.0,0.0,-0.5*R)
mol.add_atom("He",0.0,0.0, 0.0*R)
mol.add_atom("H",0.0,0.0, 1.0*R)

We can print the molecule to see its structure

In [33]:
mol.print()

   H:   0.000000    0.000000   -1.000000
  He:   0.000000    0.000000    0.000000
   H:   0.000000    0.000000    2.000000


Next, we create the interface to the Libint library. This requires the molecule object and a string containing the basis set name.
All the relevant one- and two-electron integrals are computed on initialization.

In [35]:
ints = quantel.LibintInterface("sto-3g",mol)

We can access individual integrals using "getter" functions

In [37]:
print(f"  <0|1> = {ints.overlap(0,1) :10.5f}")
print(f"<0|h|1> = {ints.oei(0,1,True) :10.5f}")
print(f"<00|11> = {ints.tei(0,0,1,1,True,False) :10.5f}")

  <0|1> =    0.71422
<0|h|1> =   -2.34953
<00|11> =    0.71103


Alternatively, we can get a numpy array containing the overlap or one-electron integrals, for example

In [42]:
s = ints.overlap_matrix()
h = ints.oei_matrix(True)
print("Overlap matrix:")
print(s)
print("\nOne-electron matrix:")
print(h)

Overlap matrix:
[[1.         0.71422174 0.22618965]
 [0.71422174 1.         0.35903206]
 [0.22618965 0.35903206 1.        ]]

One-electron matrix:
[[-2.42280842 -2.3495321  -0.63060383]
 [-2.3495321  -3.33785249 -1.0924851 ]
 [-0.63060383 -1.0924851  -1.77456513]]
